merge lab 6.0

diff --git a/tests/run-example-experiments b/tests/run-example-experiments
--- a/tests/run-example-experiments
+++ b/tests/run-example-experiments
@@ -9,23 +9,38 @@ set -exuo pipefail
 # Change into examples directory.
 cd $(dirname "$0")/../examples
 
+check () {
+    expname="$1"
+    "./${expname}.py" --all
+    properties="data/$expname-eval/properties"
+    if [[ ! -f "$properties" ]]; then
+        echo "File not found: $properties"
+        exit 1
+    fi
+    set +e
+    grep "\"unexplained_errors\": \[$" "$properties"
+    exitcode="$?"
+    set -e
+    if [[ "$exitcode" == 0 ]]; then
+        echo "Unexplained error detected in $properties"
+        exit 1
+    fi
+}
+
 pushd ff
-./ff.py --all
+check ff
 popd
 
 pushd singularity
-./singularity-exp.py 1 2 3 4
+check singularity-exp
 popd
 
 pushd vertex-cover
-./exp.py --all
+check exp
 popd
 
-./report-external-results.py --all
+check report-external-results
+check lmcut
+check showcase-options
 
-# Fast Downward only supports Python >= 3.6.
-RESULT="$(python -c 'import sys; print(sys.version_info >= (3, 6))')"
-if [ $RESULT == True ]; then
-    ./lmcut.py --all
-    ./showcase-options.py --all
-fi
+echo "Finished running example experiments"
